//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRO.Disk
{
    
    
    public class LightSourceInfo
    {
        
        private string _name;
        
        private int _radius;
        
        private int _index;
        
        // 名称
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        
        // 发光半径
        public int radius
        {
            get
            {
                return this._radius;
            }
            set
            {
                this._radius = value;
            }
        }
        
        // 索引,不填
        public int index
        {
            get
            {
                return this._index;
            }
            set
            {
                this._index = value;
            }
        }
    }
}
