//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRO.Data
{
    
    
    public class LiquidTypeInfo
    {
        
        private string typename;
        
        private System.Collections.Generic.List<System.String> availablecolors;
        
        // 类型名称
        public string typeName
        {
            get
            {
                return this.typename;
            }
            set
            {
                this.typename = value;
            }
        }
        
        // 可用颜色
        public System.Collections.Generic.List<System.String> availableColors
        {
            get
            {
                return this.availablecolors;
            }
            set
            {
                this.availablecolors = value;
            }
        }
    }
}
