//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRO.Disk
{
    
    
    public class PixelTypeInfo
    {
        
        private string typename;
        
        private System.Collections.Generic.List<System.String> availablecolors;
        
        private int _hardness;
        
        private int _durability;
        
        private bool _collider;
        
        private int fluidtype;
        
        private int fluiddensity;
        
        private int burnodds;
        
        // 类型名称
        public string typeName
        {
            get
            {
                return this.typename;
            }
            set
            {
                this.typename = value;
            }
        }
        
        // 可用颜色
        public System.Collections.Generic.List<System.String> availableColors
        {
            get
            {
                return this.availablecolors;
            }
            set
            {
                this.availablecolors = value;
            }
        }
        
        // 坚硬度
        public int hardness
        {
            get
            {
                return this._hardness;
            }
            set
            {
                this._hardness = value;
            }
        }
        
        // 耐久度
        public int durability
        {
            get
            {
                return this._durability;
            }
            set
            {
                this._durability = value;
            }
        }
        
        // 需要碰撞
        public bool collider
        {
            get
            {
                return this._collider;
            }
            set
            {
                this._collider = value;
            }
        }
        
        // 流体类型
        public int fluidType
        {
            get
            {
                return this.fluidtype;
            }
            set
            {
                this.fluidtype = value;
            }
        }
        
        // 流体密度
        public int fluidDensity
        {
            get
            {
                return this.fluiddensity;
            }
            set
            {
                this.fluiddensity = value;
            }
        }
        
        // 燃烧概率
        public int burnOdds
        {
            get
            {
                return this.burnodds;
            }
            set
            {
                this.burnodds = value;
            }
        }
    }
}
