//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRO.Disk
{
    
    
    public class PixelColorInfo
    {
        
        private string colorname;
        
        private UnityEngine.Color32 _color;
        
        private float affectslightintensity;
        
        private int lightradius;
        
        private float selfluminous;
        
        private int _index;
        
        // 颜色的名称
        public string colorName
        {
            get
            {
                return this.colorname;
            }
            set
            {
                this.colorname = value;
            }
        }
        
        // 颜色
        public UnityEngine.Color32 color
        {
            get
            {
                return this._color;
            }
            set
            {
                this._color = value;
            }
        }
        
        // 光强影响的系数
        public float affectsLightIntensity
        {
            get
            {
                return this.affectslightintensity;
            }
            set
            {
                this.affectslightintensity = value;
            }
        }
        
        // 发光半径
        public int lightRadius
        {
            get
            {
                return this.lightradius;
            }
            set
            {
                this.lightradius = value;
            }
        }
        
        // 自发光强度
        public float selfLuminous
        {
            get
            {
                return this.selfluminous;
            }
            set
            {
                this.selfluminous = value;
            }
        }
        
        // 不填
        public int index
        {
            get
            {
                return this._index;
            }
            set
            {
                this._index = value;
            }
        }
    }
}
