//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRO.Data
{
    
    
    public class PixelColorInfo
    {
        
        private string _name;
        
        private UnityEngine.Color32 _color;
        
        private bool affectslight;
        
        private string lightsourcetype;
        
        private int _index;
        
        // 名称
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        
        // 颜色
        public UnityEngine.Color32 color
        {
            get
            {
                return this._color;
            }
            set
            {
                this._color = value;
            }
        }
        
        // 是否影响光照
        public bool affectsLight
        {
            get
            {
                return this.affectslight;
            }
            set
            {
                this.affectslight = value;
            }
        }
        
        // 光源类型，为空不发光
        public string lightSourceType
        {
            get
            {
                return this.lightsourcetype;
            }
            set
            {
                this.lightsourcetype = value;
            }
        }
        
        // 不填
        public int index
        {
            get
            {
                return this._index;
            }
            set
            {
                this._index = value;
            }
        }
    }
}
