// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: BlockBaseData.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace PRO.Proto {

  /// <summary>Holder for reflection information generated from BlockBaseData.proto</summary>
  public static partial class BlockBaseDataReflection {

    #region Descriptor
    /// <summary>File descriptor for BlockBaseData.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BlockBaseDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNCbG9ja0Jhc2VEYXRhLnByb3RvEglQUk8uUHJvdG8aO1BSTy5HZW5lcmlj",
            "RnJhbWV3b3JrL1Byb3RvYnVmL0RhdGFTdHJ1Y3R1cmUvQmFzaWNEYXRhLnBy",
            "b3RvIosHCg1CbG9ja0Jhc2VEYXRhEkgKEFR5cGVOYW1lSW5kZXhEaWMYASAD",
            "KAsyLi5QUk8uUHJvdG8uQmxvY2tCYXNlRGF0YS5UeXBlTmFtZUluZGV4RGlj",
            "RW50cnkSSgoRQ29sb3JOYW1lSW5kZXhEaWMYAiADKAsyLy5QUk8uUHJvdG8u",
            "QmxvY2tCYXNlRGF0YS5Db2xvck5hbWVJbmRleERpY0VudHJ5ElAKFEJ1aWxk",
            "aW5nR3VpZEluZGV4RGljGAMgAygLMjIuUFJPLlByb3RvLkJsb2NrQmFzZURh",
            "dGEuQnVpbGRpbmdHdWlkSW5kZXhEaWNFbnRyeRI0CghBbGxQaXhlbBgKIAMo",
            "CzIiLlBSTy5Qcm90by5CbG9ja0Jhc2VEYXRhLlBpeGVsRGF0YRIzCgVCbG9j",
            "axgLIAEoCzIiLlBSTy5Qcm90by5CbG9ja0Jhc2VEYXRhLkJsb2NrRGF0YUgA",
            "Ej0KCkJhY2tncm91bmQYDCABKAsyJy5QUk8uUHJvdG8uQmxvY2tCYXNlRGF0",
            "YS5CYWNrZ3JvdW5kRGF0YUgAGjcKFVR5cGVOYW1lSW5kZXhEaWNFbnRyeRIL",
            "CgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAU6AjgBGjgKFkNvbG9yTmFtZUlu",
            "ZGV4RGljRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgFOgI4ARo7",
            "ChlCdWlsZGluZ0d1aWRJbmRleERpY0VudHJ5EgsKA2tleRgBIAEoCRINCgV2",
            "YWx1ZRgCIAEoBToCOAEaeQoJUGl4ZWxEYXRhEhEKCVR5cGVJbmRleBgBIAEo",
            "BRISCgpDb2xvckluZGV4GAIgASgFEhIKCkR1cmFiaWxpdHkYAyABKAUSGwoT",
            "QWZmZWN0c1RyYW5zcGFyZW5jeRgEIAEoAhIUCgxCdWlsZGluZ0xpc3QYBSAD",
            "KAUaoQEKCUJsb2NrRGF0YRIwChBGbHVpZFVwZGF0ZUhhc2gxGAEgAygLMhYu",
            "UFJPLlByb3RvLlZlY3RvcjJCeXRlEjAKEEZsdWlkVXBkYXRlSGFzaDIYAiAD",
            "KAsyFi5QUk8uUHJvdG8uVmVjdG9yMkJ5dGUSMAoQRmx1aWRVcGRhdGVIYXNo",
            "MxgDIAMoCzIWLlBSTy5Qcm90by5WZWN0b3IyQnl0ZRoQCg5CYWNrZ3JvdW5k",
            "RGF0YUIHCgVBZGRlZGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::PRO.Proto.BasicDataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::PRO.Proto.BlockBaseData), global::PRO.Proto.BlockBaseData.Parser, new[]{ "TypeNameIndexDic", "ColorNameIndexDic", "BuildingGuidIndexDic", "AllPixel", "Block", "Background" }, new[]{ "Added" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, null, new pbr::GeneratedClrTypeInfo(typeof(global::PRO.Proto.BlockBaseData.Types.PixelData), global::PRO.Proto.BlockBaseData.Types.PixelData.Parser, new[]{ "TypeIndex", "ColorIndex", "Durability", "AffectsTransparency", "BuildingList" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PRO.Proto.BlockBaseData.Types.BlockData), global::PRO.Proto.BlockBaseData.Types.BlockData.Parser, new[]{ "FluidUpdateHash1", "FluidUpdateHash2", "FluidUpdateHash3" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PRO.Proto.BlockBaseData.Types.BackgroundData), global::PRO.Proto.BlockBaseData.Types.BackgroundData.Parser, null, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class BlockBaseData : pb::IMessage<BlockBaseData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BlockBaseData> _parser = new pb::MessageParser<BlockBaseData>(() => new BlockBaseData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BlockBaseData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PRO.Proto.BlockBaseDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BlockBaseData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BlockBaseData(BlockBaseData other) : this() {
      typeNameIndexDic_ = other.typeNameIndexDic_.Clone();
      colorNameIndexDic_ = other.colorNameIndexDic_.Clone();
      buildingGuidIndexDic_ = other.buildingGuidIndexDic_.Clone();
      allPixel_ = other.allPixel_.Clone();
      switch (other.AddedCase) {
        case AddedOneofCase.Block:
          Block = other.Block.Clone();
          break;
        case AddedOneofCase.Background:
          Background = other.Background.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BlockBaseData Clone() {
      return new BlockBaseData(this);
    }

    /// <summary>Field number for the "TypeNameIndexDic" field.</summary>
    public const int TypeNameIndexDicFieldNumber = 1;
    private static readonly pbc::MapField<string, int>.Codec _map_typeNameIndexDic_codec
        = new pbc::MapField<string, int>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForInt32(16, 0), 10);
    private readonly pbc::MapField<string, int> typeNameIndexDic_ = new pbc::MapField<string, int>();
    /// <summary>
    /// 像素索引与类型字典
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, int> TypeNameIndexDic {
      get { return typeNameIndexDic_; }
    }

    /// <summary>Field number for the "ColorNameIndexDic" field.</summary>
    public const int ColorNameIndexDicFieldNumber = 2;
    private static readonly pbc::MapField<string, int>.Codec _map_colorNameIndexDic_codec
        = new pbc::MapField<string, int>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForInt32(16, 0), 18);
    private readonly pbc::MapField<string, int> colorNameIndexDic_ = new pbc::MapField<string, int>();
    /// <summary>
    /// 像素索引与颜色字典
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, int> ColorNameIndexDic {
      get { return colorNameIndexDic_; }
    }

    /// <summary>Field number for the "BuildingGuidIndexDic" field.</summary>
    public const int BuildingGuidIndexDicFieldNumber = 3;
    private static readonly pbc::MapField<string, int>.Codec _map_buildingGuidIndexDic_codec
        = new pbc::MapField<string, int>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForInt32(16, 0), 26);
    private readonly pbc::MapField<string, int> buildingGuidIndexDic_ = new pbc::MapField<string, int>();
    /// <summary>
    /// 建筑索引与guid字典
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, int> BuildingGuidIndexDic {
      get { return buildingGuidIndexDic_; }
    }

    /// <summary>Field number for the "AllPixel" field.</summary>
    public const int AllPixelFieldNumber = 10;
    private static readonly pb::FieldCodec<global::PRO.Proto.BlockBaseData.Types.PixelData> _repeated_allPixel_codec
        = pb::FieldCodec.ForMessage(82, global::PRO.Proto.BlockBaseData.Types.PixelData.Parser);
    private readonly pbc::RepeatedField<global::PRO.Proto.BlockBaseData.Types.PixelData> allPixel_ = new pbc::RepeatedField<global::PRO.Proto.BlockBaseData.Types.PixelData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::PRO.Proto.BlockBaseData.Types.PixelData> AllPixel {
      get { return allPixel_; }
    }

    /// <summary>Field number for the "Block" field.</summary>
    public const int BlockFieldNumber = 11;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::PRO.Proto.BlockBaseData.Types.BlockData Block {
      get { return addedCase_ == AddedOneofCase.Block ? (global::PRO.Proto.BlockBaseData.Types.BlockData) added_ : null; }
      set {
        added_ = value;
        addedCase_ = value == null ? AddedOneofCase.None : AddedOneofCase.Block;
      }
    }

    /// <summary>Field number for the "Background" field.</summary>
    public const int BackgroundFieldNumber = 12;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::PRO.Proto.BlockBaseData.Types.BackgroundData Background {
      get { return addedCase_ == AddedOneofCase.Background ? (global::PRO.Proto.BlockBaseData.Types.BackgroundData) added_ : null; }
      set {
        added_ = value;
        addedCase_ = value == null ? AddedOneofCase.None : AddedOneofCase.Background;
      }
    }

    private object added_;
    /// <summary>Enum of possible cases for the "Added" oneof.</summary>
    public enum AddedOneofCase {
      None = 0,
      Block = 11,
      Background = 12,
    }
    private AddedOneofCase addedCase_ = AddedOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AddedOneofCase AddedCase {
      get { return addedCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAdded() {
      addedCase_ = AddedOneofCase.None;
      added_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BlockBaseData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BlockBaseData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!TypeNameIndexDic.Equals(other.TypeNameIndexDic)) return false;
      if (!ColorNameIndexDic.Equals(other.ColorNameIndexDic)) return false;
      if (!BuildingGuidIndexDic.Equals(other.BuildingGuidIndexDic)) return false;
      if(!allPixel_.Equals(other.allPixel_)) return false;
      if (!object.Equals(Block, other.Block)) return false;
      if (!object.Equals(Background, other.Background)) return false;
      if (AddedCase != other.AddedCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= TypeNameIndexDic.GetHashCode();
      hash ^= ColorNameIndexDic.GetHashCode();
      hash ^= BuildingGuidIndexDic.GetHashCode();
      hash ^= allPixel_.GetHashCode();
      if (addedCase_ == AddedOneofCase.Block) hash ^= Block.GetHashCode();
      if (addedCase_ == AddedOneofCase.Background) hash ^= Background.GetHashCode();
      hash ^= (int) addedCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      typeNameIndexDic_.WriteTo(output, _map_typeNameIndexDic_codec);
      colorNameIndexDic_.WriteTo(output, _map_colorNameIndexDic_codec);
      buildingGuidIndexDic_.WriteTo(output, _map_buildingGuidIndexDic_codec);
      allPixel_.WriteTo(output, _repeated_allPixel_codec);
      if (addedCase_ == AddedOneofCase.Block) {
        output.WriteRawTag(90);
        output.WriteMessage(Block);
      }
      if (addedCase_ == AddedOneofCase.Background) {
        output.WriteRawTag(98);
        output.WriteMessage(Background);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      typeNameIndexDic_.WriteTo(ref output, _map_typeNameIndexDic_codec);
      colorNameIndexDic_.WriteTo(ref output, _map_colorNameIndexDic_codec);
      buildingGuidIndexDic_.WriteTo(ref output, _map_buildingGuidIndexDic_codec);
      allPixel_.WriteTo(ref output, _repeated_allPixel_codec);
      if (addedCase_ == AddedOneofCase.Block) {
        output.WriteRawTag(90);
        output.WriteMessage(Block);
      }
      if (addedCase_ == AddedOneofCase.Background) {
        output.WriteRawTag(98);
        output.WriteMessage(Background);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += typeNameIndexDic_.CalculateSize(_map_typeNameIndexDic_codec);
      size += colorNameIndexDic_.CalculateSize(_map_colorNameIndexDic_codec);
      size += buildingGuidIndexDic_.CalculateSize(_map_buildingGuidIndexDic_codec);
      size += allPixel_.CalculateSize(_repeated_allPixel_codec);
      if (addedCase_ == AddedOneofCase.Block) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Block);
      }
      if (addedCase_ == AddedOneofCase.Background) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Background);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BlockBaseData other) {
      if (other == null) {
        return;
      }
      typeNameIndexDic_.MergeFrom(other.typeNameIndexDic_);
      colorNameIndexDic_.MergeFrom(other.colorNameIndexDic_);
      buildingGuidIndexDic_.MergeFrom(other.buildingGuidIndexDic_);
      allPixel_.Add(other.allPixel_);
      switch (other.AddedCase) {
        case AddedOneofCase.Block:
          if (Block == null) {
            Block = new global::PRO.Proto.BlockBaseData.Types.BlockData();
          }
          Block.MergeFrom(other.Block);
          break;
        case AddedOneofCase.Background:
          if (Background == null) {
            Background = new global::PRO.Proto.BlockBaseData.Types.BackgroundData();
          }
          Background.MergeFrom(other.Background);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            typeNameIndexDic_.AddEntriesFrom(input, _map_typeNameIndexDic_codec);
            break;
          }
          case 18: {
            colorNameIndexDic_.AddEntriesFrom(input, _map_colorNameIndexDic_codec);
            break;
          }
          case 26: {
            buildingGuidIndexDic_.AddEntriesFrom(input, _map_buildingGuidIndexDic_codec);
            break;
          }
          case 82: {
            allPixel_.AddEntriesFrom(input, _repeated_allPixel_codec);
            break;
          }
          case 90: {
            global::PRO.Proto.BlockBaseData.Types.BlockData subBuilder = new global::PRO.Proto.BlockBaseData.Types.BlockData();
            if (addedCase_ == AddedOneofCase.Block) {
              subBuilder.MergeFrom(Block);
            }
            input.ReadMessage(subBuilder);
            Block = subBuilder;
            break;
          }
          case 98: {
            global::PRO.Proto.BlockBaseData.Types.BackgroundData subBuilder = new global::PRO.Proto.BlockBaseData.Types.BackgroundData();
            if (addedCase_ == AddedOneofCase.Background) {
              subBuilder.MergeFrom(Background);
            }
            input.ReadMessage(subBuilder);
            Background = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            typeNameIndexDic_.AddEntriesFrom(ref input, _map_typeNameIndexDic_codec);
            break;
          }
          case 18: {
            colorNameIndexDic_.AddEntriesFrom(ref input, _map_colorNameIndexDic_codec);
            break;
          }
          case 26: {
            buildingGuidIndexDic_.AddEntriesFrom(ref input, _map_buildingGuidIndexDic_codec);
            break;
          }
          case 82: {
            allPixel_.AddEntriesFrom(ref input, _repeated_allPixel_codec);
            break;
          }
          case 90: {
            global::PRO.Proto.BlockBaseData.Types.BlockData subBuilder = new global::PRO.Proto.BlockBaseData.Types.BlockData();
            if (addedCase_ == AddedOneofCase.Block) {
              subBuilder.MergeFrom(Block);
            }
            input.ReadMessage(subBuilder);
            Block = subBuilder;
            break;
          }
          case 98: {
            global::PRO.Proto.BlockBaseData.Types.BackgroundData subBuilder = new global::PRO.Proto.BlockBaseData.Types.BackgroundData();
            if (addedCase_ == AddedOneofCase.Background) {
              subBuilder.MergeFrom(Background);
            }
            input.ReadMessage(subBuilder);
            Background = subBuilder;
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the BlockBaseData message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class PixelData : pb::IMessage<PixelData>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<PixelData> _parser = new pb::MessageParser<PixelData>(() => new PixelData());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<PixelData> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::PRO.Proto.BlockBaseData.Descriptor.NestedTypes[3]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public PixelData() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public PixelData(PixelData other) : this() {
          typeIndex_ = other.typeIndex_;
          colorIndex_ = other.colorIndex_;
          durability_ = other.durability_;
          affectsTransparency_ = other.affectsTransparency_;
          buildingList_ = other.buildingList_.Clone();
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public PixelData Clone() {
          return new PixelData(this);
        }

        /// <summary>Field number for the "TypeIndex" field.</summary>
        public const int TypeIndexFieldNumber = 1;
        private int typeIndex_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int TypeIndex {
          get { return typeIndex_; }
          set {
            typeIndex_ = value;
          }
        }

        /// <summary>Field number for the "ColorIndex" field.</summary>
        public const int ColorIndexFieldNumber = 2;
        private int colorIndex_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int ColorIndex {
          get { return colorIndex_; }
          set {
            colorIndex_ = value;
          }
        }

        /// <summary>Field number for the "Durability" field.</summary>
        public const int DurabilityFieldNumber = 3;
        private int durability_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int Durability {
          get { return durability_; }
          set {
            durability_ = value;
          }
        }

        /// <summary>Field number for the "AffectsTransparency" field.</summary>
        public const int AffectsTransparencyFieldNumber = 4;
        private float affectsTransparency_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public float AffectsTransparency {
          get { return affectsTransparency_; }
          set {
            affectsTransparency_ = value;
          }
        }

        /// <summary>Field number for the "BuildingList" field.</summary>
        public const int BuildingListFieldNumber = 5;
        private static readonly pb::FieldCodec<int> _repeated_buildingList_codec
            = pb::FieldCodec.ForInt32(42);
        private readonly pbc::RepeatedField<int> buildingList_ = new pbc::RepeatedField<int>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::RepeatedField<int> BuildingList {
          get { return buildingList_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as PixelData);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(PixelData other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (TypeIndex != other.TypeIndex) return false;
          if (ColorIndex != other.ColorIndex) return false;
          if (Durability != other.Durability) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(AffectsTransparency, other.AffectsTransparency)) return false;
          if(!buildingList_.Equals(other.buildingList_)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (TypeIndex != 0) hash ^= TypeIndex.GetHashCode();
          if (ColorIndex != 0) hash ^= ColorIndex.GetHashCode();
          if (Durability != 0) hash ^= Durability.GetHashCode();
          if (AffectsTransparency != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(AffectsTransparency);
          hash ^= buildingList_.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (TypeIndex != 0) {
            output.WriteRawTag(8);
            output.WriteInt32(TypeIndex);
          }
          if (ColorIndex != 0) {
            output.WriteRawTag(16);
            output.WriteInt32(ColorIndex);
          }
          if (Durability != 0) {
            output.WriteRawTag(24);
            output.WriteInt32(Durability);
          }
          if (AffectsTransparency != 0F) {
            output.WriteRawTag(37);
            output.WriteFloat(AffectsTransparency);
          }
          buildingList_.WriteTo(output, _repeated_buildingList_codec);
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (TypeIndex != 0) {
            output.WriteRawTag(8);
            output.WriteInt32(TypeIndex);
          }
          if (ColorIndex != 0) {
            output.WriteRawTag(16);
            output.WriteInt32(ColorIndex);
          }
          if (Durability != 0) {
            output.WriteRawTag(24);
            output.WriteInt32(Durability);
          }
          if (AffectsTransparency != 0F) {
            output.WriteRawTag(37);
            output.WriteFloat(AffectsTransparency);
          }
          buildingList_.WriteTo(ref output, _repeated_buildingList_codec);
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (TypeIndex != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(TypeIndex);
          }
          if (ColorIndex != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(ColorIndex);
          }
          if (Durability != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(Durability);
          }
          if (AffectsTransparency != 0F) {
            size += 1 + 4;
          }
          size += buildingList_.CalculateSize(_repeated_buildingList_codec);
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(PixelData other) {
          if (other == null) {
            return;
          }
          if (other.TypeIndex != 0) {
            TypeIndex = other.TypeIndex;
          }
          if (other.ColorIndex != 0) {
            ColorIndex = other.ColorIndex;
          }
          if (other.Durability != 0) {
            Durability = other.Durability;
          }
          if (other.AffectsTransparency != 0F) {
            AffectsTransparency = other.AffectsTransparency;
          }
          buildingList_.Add(other.buildingList_);
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                TypeIndex = input.ReadInt32();
                break;
              }
              case 16: {
                ColorIndex = input.ReadInt32();
                break;
              }
              case 24: {
                Durability = input.ReadInt32();
                break;
              }
              case 37: {
                AffectsTransparency = input.ReadFloat();
                break;
              }
              case 42:
              case 40: {
                buildingList_.AddEntriesFrom(input, _repeated_buildingList_codec);
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                TypeIndex = input.ReadInt32();
                break;
              }
              case 16: {
                ColorIndex = input.ReadInt32();
                break;
              }
              case 24: {
                Durability = input.ReadInt32();
                break;
              }
              case 37: {
                AffectsTransparency = input.ReadFloat();
                break;
              }
              case 42:
              case 40: {
                buildingList_.AddEntriesFrom(ref input, _repeated_buildingList_codec);
                break;
              }
            }
          }
        }
        #endif

      }

      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class BlockData : pb::IMessage<BlockData>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<BlockData> _parser = new pb::MessageParser<BlockData>(() => new BlockData());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<BlockData> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::PRO.Proto.BlockBaseData.Descriptor.NestedTypes[4]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public BlockData() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public BlockData(BlockData other) : this() {
          fluidUpdateHash1_ = other.fluidUpdateHash1_.Clone();
          fluidUpdateHash2_ = other.fluidUpdateHash2_.Clone();
          fluidUpdateHash3_ = other.fluidUpdateHash3_.Clone();
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public BlockData Clone() {
          return new BlockData(this);
        }

        /// <summary>Field number for the "FluidUpdateHash1" field.</summary>
        public const int FluidUpdateHash1FieldNumber = 1;
        private static readonly pb::FieldCodec<global::PRO.Proto.Vector2Byte> _repeated_fluidUpdateHash1_codec
            = pb::FieldCodec.ForMessage(10, global::PRO.Proto.Vector2Byte.Parser);
        private readonly pbc::RepeatedField<global::PRO.Proto.Vector2Byte> fluidUpdateHash1_ = new pbc::RepeatedField<global::PRO.Proto.Vector2Byte>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::RepeatedField<global::PRO.Proto.Vector2Byte> FluidUpdateHash1 {
          get { return fluidUpdateHash1_; }
        }

        /// <summary>Field number for the "FluidUpdateHash2" field.</summary>
        public const int FluidUpdateHash2FieldNumber = 2;
        private static readonly pb::FieldCodec<global::PRO.Proto.Vector2Byte> _repeated_fluidUpdateHash2_codec
            = pb::FieldCodec.ForMessage(18, global::PRO.Proto.Vector2Byte.Parser);
        private readonly pbc::RepeatedField<global::PRO.Proto.Vector2Byte> fluidUpdateHash2_ = new pbc::RepeatedField<global::PRO.Proto.Vector2Byte>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::RepeatedField<global::PRO.Proto.Vector2Byte> FluidUpdateHash2 {
          get { return fluidUpdateHash2_; }
        }

        /// <summary>Field number for the "FluidUpdateHash3" field.</summary>
        public const int FluidUpdateHash3FieldNumber = 3;
        private static readonly pb::FieldCodec<global::PRO.Proto.Vector2Byte> _repeated_fluidUpdateHash3_codec
            = pb::FieldCodec.ForMessage(26, global::PRO.Proto.Vector2Byte.Parser);
        private readonly pbc::RepeatedField<global::PRO.Proto.Vector2Byte> fluidUpdateHash3_ = new pbc::RepeatedField<global::PRO.Proto.Vector2Byte>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::RepeatedField<global::PRO.Proto.Vector2Byte> FluidUpdateHash3 {
          get { return fluidUpdateHash3_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as BlockData);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(BlockData other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if(!fluidUpdateHash1_.Equals(other.fluidUpdateHash1_)) return false;
          if(!fluidUpdateHash2_.Equals(other.fluidUpdateHash2_)) return false;
          if(!fluidUpdateHash3_.Equals(other.fluidUpdateHash3_)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          hash ^= fluidUpdateHash1_.GetHashCode();
          hash ^= fluidUpdateHash2_.GetHashCode();
          hash ^= fluidUpdateHash3_.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          fluidUpdateHash1_.WriteTo(output, _repeated_fluidUpdateHash1_codec);
          fluidUpdateHash2_.WriteTo(output, _repeated_fluidUpdateHash2_codec);
          fluidUpdateHash3_.WriteTo(output, _repeated_fluidUpdateHash3_codec);
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          fluidUpdateHash1_.WriteTo(ref output, _repeated_fluidUpdateHash1_codec);
          fluidUpdateHash2_.WriteTo(ref output, _repeated_fluidUpdateHash2_codec);
          fluidUpdateHash3_.WriteTo(ref output, _repeated_fluidUpdateHash3_codec);
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          size += fluidUpdateHash1_.CalculateSize(_repeated_fluidUpdateHash1_codec);
          size += fluidUpdateHash2_.CalculateSize(_repeated_fluidUpdateHash2_codec);
          size += fluidUpdateHash3_.CalculateSize(_repeated_fluidUpdateHash3_codec);
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(BlockData other) {
          if (other == null) {
            return;
          }
          fluidUpdateHash1_.Add(other.fluidUpdateHash1_);
          fluidUpdateHash2_.Add(other.fluidUpdateHash2_);
          fluidUpdateHash3_.Add(other.fluidUpdateHash3_);
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                fluidUpdateHash1_.AddEntriesFrom(input, _repeated_fluidUpdateHash1_codec);
                break;
              }
              case 18: {
                fluidUpdateHash2_.AddEntriesFrom(input, _repeated_fluidUpdateHash2_codec);
                break;
              }
              case 26: {
                fluidUpdateHash3_.AddEntriesFrom(input, _repeated_fluidUpdateHash3_codec);
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                fluidUpdateHash1_.AddEntriesFrom(ref input, _repeated_fluidUpdateHash1_codec);
                break;
              }
              case 18: {
                fluidUpdateHash2_.AddEntriesFrom(ref input, _repeated_fluidUpdateHash2_codec);
                break;
              }
              case 26: {
                fluidUpdateHash3_.AddEntriesFrom(ref input, _repeated_fluidUpdateHash3_codec);
                break;
              }
            }
          }
        }
        #endif

      }

      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class BackgroundData : pb::IMessage<BackgroundData>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<BackgroundData> _parser = new pb::MessageParser<BackgroundData>(() => new BackgroundData());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<BackgroundData> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::PRO.Proto.BlockBaseData.Descriptor.NestedTypes[5]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public BackgroundData() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public BackgroundData(BackgroundData other) : this() {
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public BackgroundData Clone() {
          return new BackgroundData(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as BackgroundData);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(BackgroundData other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(BackgroundData other) {
          if (other == null) {
            return;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
namespace PRO.Proto
{
public partial class BlockBaseData
{
public void Clear()
{
TypeNameIndexDic.Clear();
ColorNameIndexDic.Clear();
BuildingGuidIndexDic.Clear();
foreach(var item in AllPixel)
{
item.Clear();
PRO.Proto.ProtoPool.PutIn(item);
}
AllPixel.Clear();
if(Block!=null)
{
Block.Clear();
PRO.Proto.ProtoPool.PutIn(Block);
Block = null;
}
if(Background!=null)
{
Background.Clear();
PRO.Proto.ProtoPool.PutIn(Background);
Background = null;
}
}
public partial class Types
{
public partial class PixelData
{
public void Clear()
{
TypeIndex = 0;
ColorIndex = 0;
Durability = 0;
AffectsTransparency = 0;
BuildingList.Clear();
}
public void ClearPutIn()
{
Clear();
PRO.Proto.ProtoPool.PutIn(this);
}
}
public partial class BlockData
{
public void Clear()
{
foreach(var item in FluidUpdateHash1)
{
item.Clear();
PRO.Proto.ProtoPool.PutIn(item);
}
FluidUpdateHash1.Clear();
foreach(var item in FluidUpdateHash2)
{
item.Clear();
PRO.Proto.ProtoPool.PutIn(item);
}
FluidUpdateHash2.Clear();
foreach(var item in FluidUpdateHash3)
{
item.Clear();
PRO.Proto.ProtoPool.PutIn(item);
}
FluidUpdateHash3.Clear();
}
public void ClearPutIn()
{
Clear();
PRO.Proto.ProtoPool.PutIn(this);
}
}
public partial class BackgroundData
{
public void Clear()
{
}
public void ClearPutIn()
{
Clear();
PRO.Proto.ProtoPool.PutIn(this);
}
}
}
public void ClearPutIn()
{
Clear();
PRO.Proto.ProtoPool.PutIn(this);
}
}

}
