// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ParticleData.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace PRO.Proto {

  /// <summary>Holder for reflection information generated from ParticleData.proto</summary>
  public static partial class ParticleDataReflection {

    #region Descriptor
    /// <summary>File descriptor for ParticleData.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ParticleDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJQYXJ0aWNsZURhdGEucHJvdG8SCVBSTy5Qcm90bxo7UFJPLkdlbmVyaWNG",
            "cmFtZXdvcmsvUHJvdG9idWYvRGF0YVN0cnVjdHVyZS9CYXNpY0RhdGEucHJv",
            "dG8i5AEKDFBhcnRpY2xlRGF0YRIQCghMb2FkUGF0aBgBIAEoCRInCglUcmFu",
            "c2Zvcm0YAiABKAsyFC5QUk8uUHJvdG8uVHJhbnNmb3JtEisKC1JpZ2lkYm9k",
            "eTJEGAMgASgLMhYuUFJPLlByb3RvLlJpZ2lkYm9keTJEEi8KEFN1cnZpdmVU",
            "aW1lUmFuZ2UYBCABKAsyFS5QUk8uUHJvdG8uVmVjdG9yMkludBISCgpSZW1h",
            "aW5UaW1lGAUgASgFEhMKC0VsYXBzZWRUaW1lGAYgASgFEhIKCkV4dGVuZERh",
            "dGEYDyABKAxiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::PRO.Proto.BasicDataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::PRO.Proto.ParticleData), global::PRO.Proto.ParticleData.Parser, new[]{ "LoadPath", "Transform", "Rigidbody2D", "SurviveTimeRange", "RemainTime", "ElapsedTime", "ExtendData" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ParticleData : pb::IMessage<ParticleData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ParticleData> _parser = new pb::MessageParser<ParticleData>(() => new ParticleData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ParticleData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PRO.Proto.ParticleDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ParticleData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ParticleData(ParticleData other) : this() {
      loadPath_ = other.loadPath_;
      transform_ = other.transform_ != null ? other.transform_.Clone() : null;
      rigidbody2D_ = other.rigidbody2D_ != null ? other.rigidbody2D_.Clone() : null;
      surviveTimeRange_ = other.surviveTimeRange_ != null ? other.surviveTimeRange_.Clone() : null;
      remainTime_ = other.remainTime_;
      elapsedTime_ = other.elapsedTime_;
      extendData_ = other.extendData_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ParticleData Clone() {
      return new ParticleData(this);
    }

    /// <summary>Field number for the "LoadPath" field.</summary>
    public const int LoadPathFieldNumber = 1;
    private string loadPath_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string LoadPath {
      get { return loadPath_; }
      set {
        loadPath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Transform" field.</summary>
    public const int TransformFieldNumber = 2;
    private global::PRO.Proto.Transform transform_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::PRO.Proto.Transform Transform {
      get { return transform_; }
      set {
        transform_ = value;
      }
    }

    /// <summary>Field number for the "Rigidbody2D" field.</summary>
    public const int Rigidbody2DFieldNumber = 3;
    private global::PRO.Proto.Rigidbody2D rigidbody2D_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::PRO.Proto.Rigidbody2D Rigidbody2D {
      get { return rigidbody2D_; }
      set {
        rigidbody2D_ = value;
      }
    }

    /// <summary>Field number for the "SurviveTimeRange" field.</summary>
    public const int SurviveTimeRangeFieldNumber = 4;
    private global::PRO.Proto.Vector2Int surviveTimeRange_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::PRO.Proto.Vector2Int SurviveTimeRange {
      get { return surviveTimeRange_; }
      set {
        surviveTimeRange_ = value;
      }
    }

    /// <summary>Field number for the "RemainTime" field.</summary>
    public const int RemainTimeFieldNumber = 5;
    private int remainTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int RemainTime {
      get { return remainTime_; }
      set {
        remainTime_ = value;
      }
    }

    /// <summary>Field number for the "ElapsedTime" field.</summary>
    public const int ElapsedTimeFieldNumber = 6;
    private int elapsedTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ElapsedTime {
      get { return elapsedTime_; }
      set {
        elapsedTime_ = value;
      }
    }

    /// <summary>Field number for the "ExtendData" field.</summary>
    public const int ExtendDataFieldNumber = 15;
    private pb::ByteString extendData_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString ExtendData {
      get { return extendData_; }
      set {
        extendData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ParticleData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ParticleData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LoadPath != other.LoadPath) return false;
      if (!object.Equals(Transform, other.Transform)) return false;
      if (!object.Equals(Rigidbody2D, other.Rigidbody2D)) return false;
      if (!object.Equals(SurviveTimeRange, other.SurviveTimeRange)) return false;
      if (RemainTime != other.RemainTime) return false;
      if (ElapsedTime != other.ElapsedTime) return false;
      if (ExtendData != other.ExtendData) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (LoadPath.Length != 0) hash ^= LoadPath.GetHashCode();
      if (transform_ != null) hash ^= Transform.GetHashCode();
      if (rigidbody2D_ != null) hash ^= Rigidbody2D.GetHashCode();
      if (surviveTimeRange_ != null) hash ^= SurviveTimeRange.GetHashCode();
      if (RemainTime != 0) hash ^= RemainTime.GetHashCode();
      if (ElapsedTime != 0) hash ^= ElapsedTime.GetHashCode();
      if (ExtendData.Length != 0) hash ^= ExtendData.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (LoadPath.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(LoadPath);
      }
      if (transform_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Transform);
      }
      if (rigidbody2D_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Rigidbody2D);
      }
      if (surviveTimeRange_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(SurviveTimeRange);
      }
      if (RemainTime != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(RemainTime);
      }
      if (ElapsedTime != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(ElapsedTime);
      }
      if (ExtendData.Length != 0) {
        output.WriteRawTag(122);
        output.WriteBytes(ExtendData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (LoadPath.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(LoadPath);
      }
      if (transform_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Transform);
      }
      if (rigidbody2D_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Rigidbody2D);
      }
      if (surviveTimeRange_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(SurviveTimeRange);
      }
      if (RemainTime != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(RemainTime);
      }
      if (ElapsedTime != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(ElapsedTime);
      }
      if (ExtendData.Length != 0) {
        output.WriteRawTag(122);
        output.WriteBytes(ExtendData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (LoadPath.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LoadPath);
      }
      if (transform_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Transform);
      }
      if (rigidbody2D_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Rigidbody2D);
      }
      if (surviveTimeRange_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SurviveTimeRange);
      }
      if (RemainTime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RemainTime);
      }
      if (ElapsedTime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ElapsedTime);
      }
      if (ExtendData.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(ExtendData);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ParticleData other) {
      if (other == null) {
        return;
      }
      if (other.LoadPath.Length != 0) {
        LoadPath = other.LoadPath;
      }
      if (other.transform_ != null) {
        if (transform_ == null) {
          Transform = new global::PRO.Proto.Transform();
        }
        Transform.MergeFrom(other.Transform);
      }
      if (other.rigidbody2D_ != null) {
        if (rigidbody2D_ == null) {
          Rigidbody2D = new global::PRO.Proto.Rigidbody2D();
        }
        Rigidbody2D.MergeFrom(other.Rigidbody2D);
      }
      if (other.surviveTimeRange_ != null) {
        if (surviveTimeRange_ == null) {
          SurviveTimeRange = new global::PRO.Proto.Vector2Int();
        }
        SurviveTimeRange.MergeFrom(other.SurviveTimeRange);
      }
      if (other.RemainTime != 0) {
        RemainTime = other.RemainTime;
      }
      if (other.ElapsedTime != 0) {
        ElapsedTime = other.ElapsedTime;
      }
      if (other.ExtendData.Length != 0) {
        ExtendData = other.ExtendData;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            LoadPath = input.ReadString();
            break;
          }
          case 18: {
            if (transform_ == null) {
              Transform = new global::PRO.Proto.Transform();
            }
            input.ReadMessage(Transform);
            break;
          }
          case 26: {
            if (rigidbody2D_ == null) {
              Rigidbody2D = new global::PRO.Proto.Rigidbody2D();
            }
            input.ReadMessage(Rigidbody2D);
            break;
          }
          case 34: {
            if (surviveTimeRange_ == null) {
              SurviveTimeRange = new global::PRO.Proto.Vector2Int();
            }
            input.ReadMessage(SurviveTimeRange);
            break;
          }
          case 40: {
            RemainTime = input.ReadInt32();
            break;
          }
          case 48: {
            ElapsedTime = input.ReadInt32();
            break;
          }
          case 122: {
            ExtendData = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            LoadPath = input.ReadString();
            break;
          }
          case 18: {
            if (transform_ == null) {
              Transform = new global::PRO.Proto.Transform();
            }
            input.ReadMessage(Transform);
            break;
          }
          case 26: {
            if (rigidbody2D_ == null) {
              Rigidbody2D = new global::PRO.Proto.Rigidbody2D();
            }
            input.ReadMessage(Rigidbody2D);
            break;
          }
          case 34: {
            if (surviveTimeRange_ == null) {
              SurviveTimeRange = new global::PRO.Proto.Vector2Int();
            }
            input.ReadMessage(SurviveTimeRange);
            break;
          }
          case 40: {
            RemainTime = input.ReadInt32();
            break;
          }
          case 48: {
            ElapsedTime = input.ReadInt32();
            break;
          }
          case 122: {
            ExtendData = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
namespace PRO.Proto
{
public partial class ParticleData
{
public void Clear()
{
LoadPath = null;
if(Transform!=null)
{
Transform.Clear();
PRO.Proto.ProtoPool.PutIn(Transform);
Transform = null;
}
if(Rigidbody2D!=null)
{
Rigidbody2D.Clear();
PRO.Proto.ProtoPool.PutIn(Rigidbody2D);
Rigidbody2D = null;
}
if(SurviveTimeRange!=null)
{
SurviveTimeRange.Clear();
PRO.Proto.ProtoPool.PutIn(SurviveTimeRange);
SurviveTimeRange = null;
}
RemainTime = 0;
ElapsedTime = 0;
if(ExtendData!=null)
{
Google.Protobuf.ByteString.PutIn(ExtendData);
ExtendData = null;
}
}
public void ClearPutIn()
{
Clear();
PRO.Proto.ProtoPool.PutIn(this);
}
}

}
