// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: RoleInfoData.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace PRO.Proto {

  /// <summary>Holder for reflection information generated from RoleInfoData.proto</summary>
  public static partial class RoleInfoDataReflection {

    #region Descriptor
    /// <summary>File descriptor for RoleInfoData.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RoleInfoDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJSb2xlSW5mb0RhdGEucHJvdG8SCVBSTy5Qcm90byLRAQoMUm9sZUluZm9E",
            "YXRhEg4KBlZhbHVlMRgBIAEoBRIOCgZWYWx1ZTIYAiABKAUSDgoGVmFsdWUz",
            "GAMgASgFEg4KBlZhbHVlNBgEIAMoBRIOCgZ2YWx1ZTUYBSABKAISDgoGdmFs",
            "dWU2GAYgASgCEg4KBnZhbHVlNxgHIAEoAhIOCgZ2YWx1ZTgYCCABKAISDgoG",
            "dmFsdWU5GAkgASgFEg8KB3ZhbHVlMTAYCiABKAUSDwoHdmFsdWUxMRgLIAEo",
            "BRIPCgd2YWx1ZTEyGAwgASgFYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::PRO.Proto.RoleInfoData), global::PRO.Proto.RoleInfoData.Parser, new[]{ "Value1", "Value2", "Value3", "Value4", "Value5", "Value6", "Value7", "Value8", "Value9", "Value10", "Value11", "Value12" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class RoleInfoData : pb::IMessage<RoleInfoData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RoleInfoData> _parser = new pb::MessageParser<RoleInfoData>(() => new RoleInfoData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RoleInfoData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PRO.Proto.RoleInfoDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RoleInfoData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RoleInfoData(RoleInfoData other) : this() {
      value1_ = other.value1_;
      value2_ = other.value2_;
      value3_ = other.value3_;
      value4_ = other.value4_.Clone();
      value5_ = other.value5_;
      value6_ = other.value6_;
      value7_ = other.value7_;
      value8_ = other.value8_;
      value9_ = other.value9_;
      value10_ = other.value10_;
      value11_ = other.value11_;
      value12_ = other.value12_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RoleInfoData Clone() {
      return new RoleInfoData(this);
    }

    /// <summary>Field number for the "Value1" field.</summary>
    public const int Value1FieldNumber = 1;
    private int value1_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Value1 {
      get { return value1_; }
      set {
        value1_ = value;
      }
    }

    /// <summary>Field number for the "Value2" field.</summary>
    public const int Value2FieldNumber = 2;
    private int value2_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Value2 {
      get { return value2_; }
      set {
        value2_ = value;
      }
    }

    /// <summary>Field number for the "Value3" field.</summary>
    public const int Value3FieldNumber = 3;
    private int value3_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Value3 {
      get { return value3_; }
      set {
        value3_ = value;
      }
    }

    /// <summary>Field number for the "Value4" field.</summary>
    public const int Value4FieldNumber = 4;
    private static readonly pb::FieldCodec<int> _repeated_value4_codec
        = pb::FieldCodec.ForInt32(34);
    private readonly pbc::RepeatedField<int> value4_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> Value4 {
      get { return value4_; }
    }

    /// <summary>Field number for the "value5" field.</summary>
    public const int Value5FieldNumber = 5;
    private float value5_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Value5 {
      get { return value5_; }
      set {
        value5_ = value;
      }
    }

    /// <summary>Field number for the "value6" field.</summary>
    public const int Value6FieldNumber = 6;
    private float value6_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Value6 {
      get { return value6_; }
      set {
        value6_ = value;
      }
    }

    /// <summary>Field number for the "value7" field.</summary>
    public const int Value7FieldNumber = 7;
    private float value7_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Value7 {
      get { return value7_; }
      set {
        value7_ = value;
      }
    }

    /// <summary>Field number for the "value8" field.</summary>
    public const int Value8FieldNumber = 8;
    private float value8_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Value8 {
      get { return value8_; }
      set {
        value8_ = value;
      }
    }

    /// <summary>Field number for the "value9" field.</summary>
    public const int Value9FieldNumber = 9;
    private int value9_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Value9 {
      get { return value9_; }
      set {
        value9_ = value;
      }
    }

    /// <summary>Field number for the "value10" field.</summary>
    public const int Value10FieldNumber = 10;
    private int value10_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Value10 {
      get { return value10_; }
      set {
        value10_ = value;
      }
    }

    /// <summary>Field number for the "value11" field.</summary>
    public const int Value11FieldNumber = 11;
    private int value11_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Value11 {
      get { return value11_; }
      set {
        value11_ = value;
      }
    }

    /// <summary>Field number for the "value12" field.</summary>
    public const int Value12FieldNumber = 12;
    private int value12_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Value12 {
      get { return value12_; }
      set {
        value12_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RoleInfoData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RoleInfoData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Value1 != other.Value1) return false;
      if (Value2 != other.Value2) return false;
      if (Value3 != other.Value3) return false;
      if(!value4_.Equals(other.value4_)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Value5, other.Value5)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Value6, other.Value6)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Value7, other.Value7)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Value8, other.Value8)) return false;
      if (Value9 != other.Value9) return false;
      if (Value10 != other.Value10) return false;
      if (Value11 != other.Value11) return false;
      if (Value12 != other.Value12) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Value1 != 0) hash ^= Value1.GetHashCode();
      if (Value2 != 0) hash ^= Value2.GetHashCode();
      if (Value3 != 0) hash ^= Value3.GetHashCode();
      hash ^= value4_.GetHashCode();
      if (Value5 != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Value5);
      if (Value6 != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Value6);
      if (Value7 != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Value7);
      if (Value8 != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Value8);
      if (Value9 != 0) hash ^= Value9.GetHashCode();
      if (Value10 != 0) hash ^= Value10.GetHashCode();
      if (Value11 != 0) hash ^= Value11.GetHashCode();
      if (Value12 != 0) hash ^= Value12.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Value1 != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Value1);
      }
      if (Value2 != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Value2);
      }
      if (Value3 != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Value3);
      }
      value4_.WriteTo(output, _repeated_value4_codec);
      if (Value5 != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(Value5);
      }
      if (Value6 != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(Value6);
      }
      if (Value7 != 0F) {
        output.WriteRawTag(61);
        output.WriteFloat(Value7);
      }
      if (Value8 != 0F) {
        output.WriteRawTag(69);
        output.WriteFloat(Value8);
      }
      if (Value9 != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(Value9);
      }
      if (Value10 != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(Value10);
      }
      if (Value11 != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(Value11);
      }
      if (Value12 != 0) {
        output.WriteRawTag(96);
        output.WriteInt32(Value12);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Value1 != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Value1);
      }
      if (Value2 != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Value2);
      }
      if (Value3 != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Value3);
      }
      value4_.WriteTo(ref output, _repeated_value4_codec);
      if (Value5 != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(Value5);
      }
      if (Value6 != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(Value6);
      }
      if (Value7 != 0F) {
        output.WriteRawTag(61);
        output.WriteFloat(Value7);
      }
      if (Value8 != 0F) {
        output.WriteRawTag(69);
        output.WriteFloat(Value8);
      }
      if (Value9 != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(Value9);
      }
      if (Value10 != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(Value10);
      }
      if (Value11 != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(Value11);
      }
      if (Value12 != 0) {
        output.WriteRawTag(96);
        output.WriteInt32(Value12);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Value1 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Value1);
      }
      if (Value2 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Value2);
      }
      if (Value3 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Value3);
      }
      size += value4_.CalculateSize(_repeated_value4_codec);
      if (Value5 != 0F) {
        size += 1 + 4;
      }
      if (Value6 != 0F) {
        size += 1 + 4;
      }
      if (Value7 != 0F) {
        size += 1 + 4;
      }
      if (Value8 != 0F) {
        size += 1 + 4;
      }
      if (Value9 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Value9);
      }
      if (Value10 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Value10);
      }
      if (Value11 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Value11);
      }
      if (Value12 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Value12);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RoleInfoData other) {
      if (other == null) {
        return;
      }
      if (other.Value1 != 0) {
        Value1 = other.Value1;
      }
      if (other.Value2 != 0) {
        Value2 = other.Value2;
      }
      if (other.Value3 != 0) {
        Value3 = other.Value3;
      }
      value4_.Add(other.value4_);
      if (other.Value5 != 0F) {
        Value5 = other.Value5;
      }
      if (other.Value6 != 0F) {
        Value6 = other.Value6;
      }
      if (other.Value7 != 0F) {
        Value7 = other.Value7;
      }
      if (other.Value8 != 0F) {
        Value8 = other.Value8;
      }
      if (other.Value9 != 0) {
        Value9 = other.Value9;
      }
      if (other.Value10 != 0) {
        Value10 = other.Value10;
      }
      if (other.Value11 != 0) {
        Value11 = other.Value11;
      }
      if (other.Value12 != 0) {
        Value12 = other.Value12;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Value1 = input.ReadInt32();
            break;
          }
          case 16: {
            Value2 = input.ReadInt32();
            break;
          }
          case 24: {
            Value3 = input.ReadInt32();
            break;
          }
          case 34:
          case 32: {
            value4_.AddEntriesFrom(input, _repeated_value4_codec);
            break;
          }
          case 45: {
            Value5 = input.ReadFloat();
            break;
          }
          case 53: {
            Value6 = input.ReadFloat();
            break;
          }
          case 61: {
            Value7 = input.ReadFloat();
            break;
          }
          case 69: {
            Value8 = input.ReadFloat();
            break;
          }
          case 72: {
            Value9 = input.ReadInt32();
            break;
          }
          case 80: {
            Value10 = input.ReadInt32();
            break;
          }
          case 88: {
            Value11 = input.ReadInt32();
            break;
          }
          case 96: {
            Value12 = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Value1 = input.ReadInt32();
            break;
          }
          case 16: {
            Value2 = input.ReadInt32();
            break;
          }
          case 24: {
            Value3 = input.ReadInt32();
            break;
          }
          case 34:
          case 32: {
            value4_.AddEntriesFrom(ref input, _repeated_value4_codec);
            break;
          }
          case 45: {
            Value5 = input.ReadFloat();
            break;
          }
          case 53: {
            Value6 = input.ReadFloat();
            break;
          }
          case 61: {
            Value7 = input.ReadFloat();
            break;
          }
          case 69: {
            Value8 = input.ReadFloat();
            break;
          }
          case 72: {
            Value9 = input.ReadInt32();
            break;
          }
          case 80: {
            Value10 = input.ReadInt32();
            break;
          }
          case 88: {
            Value11 = input.ReadInt32();
            break;
          }
          case 96: {
            Value12 = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
namespace PRO.Proto
{
public partial class RoleInfoData
{
public void Clear()
{
Value1 = 0;
Value2 = 0;
Value3 = 0;
Value4.Clear();
Value5 = 0;
Value6 = 0;
Value7 = 0;
Value8 = 0;
Value9 = 0;
Value10 = 0;
Value11 = 0;
Value12 = 0;
}
public void ClearPutIn()
{
Clear();
PRO.Proto.ProtoPool.PutIn(this);
}
}

}
