// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: SkillPlayerAgentData.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace PRO.Proto {

  /// <summary>Holder for reflection information generated from SkillPlayerAgentData.proto</summary>
  public static partial class SkillPlayerAgentDataReflection {

    #region Descriptor
    /// <summary>File descriptor for SkillPlayerAgentData.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SkillPlayerAgentDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChpTa2lsbFBsYXllckFnZW50RGF0YS5wcm90bxIJUFJPLlByb3RvInEKFFNr",
            "aWxsUGxheWVyQWdlbnREYXRhEgwKBFBsYXkYASABKAgSDAoEVGltZRgCIAEo",
            "AhIQCghOb3dGcmFtZRgDIAEoBRIUCgxJZGxlTG9hZFBhdGgYBCABKAkSFQoN",
            "U2tpbGxMb2FkUGF0aBgFIAEoCWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::PRO.Proto.SkillPlayerAgentData), global::PRO.Proto.SkillPlayerAgentData.Parser, new[]{ "Play", "Time", "NowFrame", "IdleLoadPath", "SkillLoadPath" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SkillPlayerAgentData : pb::IMessage<SkillPlayerAgentData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SkillPlayerAgentData> _parser = new pb::MessageParser<SkillPlayerAgentData>(() => new SkillPlayerAgentData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SkillPlayerAgentData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PRO.Proto.SkillPlayerAgentDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SkillPlayerAgentData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SkillPlayerAgentData(SkillPlayerAgentData other) : this() {
      play_ = other.play_;
      time_ = other.time_;
      nowFrame_ = other.nowFrame_;
      idleLoadPath_ = other.idleLoadPath_;
      skillLoadPath_ = other.skillLoadPath_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SkillPlayerAgentData Clone() {
      return new SkillPlayerAgentData(this);
    }

    /// <summary>Field number for the "Play" field.</summary>
    public const int PlayFieldNumber = 1;
    private bool play_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Play {
      get { return play_; }
      set {
        play_ = value;
      }
    }

    /// <summary>Field number for the "Time" field.</summary>
    public const int TimeFieldNumber = 2;
    private float time_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Time {
      get { return time_; }
      set {
        time_ = value;
      }
    }

    /// <summary>Field number for the "NowFrame" field.</summary>
    public const int NowFrameFieldNumber = 3;
    private int nowFrame_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NowFrame {
      get { return nowFrame_; }
      set {
        nowFrame_ = value;
      }
    }

    /// <summary>Field number for the "IdleLoadPath" field.</summary>
    public const int IdleLoadPathFieldNumber = 4;
    private string idleLoadPath_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string IdleLoadPath {
      get { return idleLoadPath_; }
      set {
        idleLoadPath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "SkillLoadPath" field.</summary>
    public const int SkillLoadPathFieldNumber = 5;
    private string skillLoadPath_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SkillLoadPath {
      get { return skillLoadPath_; }
      set {
        skillLoadPath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SkillPlayerAgentData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SkillPlayerAgentData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Play != other.Play) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Time, other.Time)) return false;
      if (NowFrame != other.NowFrame) return false;
      if (IdleLoadPath != other.IdleLoadPath) return false;
      if (SkillLoadPath != other.SkillLoadPath) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Play != false) hash ^= Play.GetHashCode();
      if (Time != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Time);
      if (NowFrame != 0) hash ^= NowFrame.GetHashCode();
      if (IdleLoadPath.Length != 0) hash ^= IdleLoadPath.GetHashCode();
      if (SkillLoadPath.Length != 0) hash ^= SkillLoadPath.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Play != false) {
        output.WriteRawTag(8);
        output.WriteBool(Play);
      }
      if (Time != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Time);
      }
      if (NowFrame != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(NowFrame);
      }
      if (IdleLoadPath.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(IdleLoadPath);
      }
      if (SkillLoadPath.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(SkillLoadPath);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Play != false) {
        output.WriteRawTag(8);
        output.WriteBool(Play);
      }
      if (Time != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Time);
      }
      if (NowFrame != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(NowFrame);
      }
      if (IdleLoadPath.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(IdleLoadPath);
      }
      if (SkillLoadPath.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(SkillLoadPath);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Play != false) {
        size += 1 + 1;
      }
      if (Time != 0F) {
        size += 1 + 4;
      }
      if (NowFrame != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NowFrame);
      }
      if (IdleLoadPath.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IdleLoadPath);
      }
      if (SkillLoadPath.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SkillLoadPath);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SkillPlayerAgentData other) {
      if (other == null) {
        return;
      }
      if (other.Play != false) {
        Play = other.Play;
      }
      if (other.Time != 0F) {
        Time = other.Time;
      }
      if (other.NowFrame != 0) {
        NowFrame = other.NowFrame;
      }
      if (other.IdleLoadPath.Length != 0) {
        IdleLoadPath = other.IdleLoadPath;
      }
      if (other.SkillLoadPath.Length != 0) {
        SkillLoadPath = other.SkillLoadPath;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Play = input.ReadBool();
            break;
          }
          case 21: {
            Time = input.ReadFloat();
            break;
          }
          case 24: {
            NowFrame = input.ReadInt32();
            break;
          }
          case 34: {
            IdleLoadPath = input.ReadString();
            break;
          }
          case 42: {
            SkillLoadPath = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Play = input.ReadBool();
            break;
          }
          case 21: {
            Time = input.ReadFloat();
            break;
          }
          case 24: {
            NowFrame = input.ReadInt32();
            break;
          }
          case 34: {
            IdleLoadPath = input.ReadString();
            break;
          }
          case 42: {
            SkillLoadPath = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
namespace PRO.Proto
{
public partial class SkillPlayerAgentData
{
public void Clear()
{
Play = false;
Time = 0;
NowFrame = 0;
IdleLoadPath = string.Empty;
SkillLoadPath = string.Empty;
}
public void ClearPutIn()
{
Clear();
PRO.Proto.ProtoPool.PutIn(this);
}
}

}
