// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace PRO.BT.Flat.Tool
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct DistanceAssessment_Vector2 : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static DistanceAssessment_Vector2 GetRootAsDistanceAssessment_Vector2(ByteBuffer _bb) { return GetRootAsDistanceAssessment_Vector2(_bb, new DistanceAssessment_Vector2()); }
  public static DistanceAssessment_Vector2 GetRootAsDistanceAssessment_Vector2(ByteBuffer _bb, DistanceAssessment_Vector2 obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DistanceAssessment_Vector2 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartDistanceAssessment_Vector2(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<PRO.BT.Flat.Tool.DistanceAssessment_Vector2> EndDistanceAssessment_Vector2(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<PRO.BT.Flat.Tool.DistanceAssessment_Vector2>(o);
  }
}


static public class DistanceAssessment_Vector2Verify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
