//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRO.Disk
{
    
    
    public class PixelTypeInfo
    {
        
        private string typename;
        
        private System.Collections.Generic.HashSet<System.String> _tags;
        
        private string[] availablecolors;
        
        private int _hardness;
        
        private int _durability;
        
        private bool _collider;
        
        private int fluidtype;
        
        private int fluiddensity;
        
        private int burnodds;
        
        private UnityEngine.Vector2Int burntimerange;
        
        private string[] electricitypixle;
        
        /// <summary>
        ///类型名称
        ///</summary>
        public string typeName
        {
            get
            {
                return this.typename;
            }
            set
            {
                this.typename = value;
            }
        }
        
        /// <summary>
        ///标签
        ///</summary>
        public System.Collections.Generic.HashSet<System.String> tags
        {
            get
            {
                return this._tags;
            }
            set
            {
                this._tags = value;
            }
        }
        
        /// <summary>
        ///可用颜色
        ///</summary>
        public string[] availableColors
        {
            get
            {
                return this.availablecolors;
            }
            set
            {
                this.availablecolors = value;
            }
        }
        
        /// <summary>
        ///坚硬度
        ///</summary>
        public int hardness
        {
            get
            {
                return this._hardness;
            }
            set
            {
                this._hardness = value;
            }
        }
        
        /// <summary>
        ///耐久度
        ///</summary>
        public int durability
        {
            get
            {
                return this._durability;
            }
            set
            {
                this._durability = value;
            }
        }
        
        /// <summary>
        ///需要碰撞
        ///</summary>
        public bool collider
        {
            get
            {
                return this._collider;
            }
            set
            {
                this._collider = value;
            }
        }
        
        /// <summary>
        ///流体类型
        ///</summary>
        public int fluidType
        {
            get
            {
                return this.fluidtype;
            }
            set
            {
                this.fluidtype = value;
            }
        }
        
        /// <summary>
        ///流体密度
        ///</summary>
        public int fluidDensity
        {
            get
            {
                return this.fluiddensity;
            }
            set
            {
                this.fluiddensity = value;
            }
        }
        
        /// <summary>
        ///燃烧概率
        ///</summary>
        public int burnOdds
        {
            get
            {
                return this.burnodds;
            }
            set
            {
                this.burnodds = value;
            }
        }
        
        /// <summary>
        ///燃烧时间范围ms
        ///</summary>
        public UnityEngine.Vector2Int burnTimeRange
        {
            get
            {
                return this.burntimerange;
            }
            set
            {
                this.burntimerange = value;
            }
        }
        
        /// <summary>
        ///带电与导电像素相互转换，需要输入相互转换的类型与颜色
        ///</summary>
        public string[] electricityPixle
        {
            get
            {
                return this.electricitypixle;
            }
            set
            {
                this.electricitypixle = value;
            }
        }
    }
}
