// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace PRO.Skill.Flat
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct OperateRecord_RaySelect : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static OperateRecord_RaySelect GetRootAsOperateRecord_RaySelect(ByteBuffer _bb) { return GetRootAsOperateRecord_RaySelect(_bb, new OperateRecord_RaySelect()); }
  public static OperateRecord_RaySelect GetRootAsOperateRecord_RaySelect(ByteBuffer _bb, OperateRecord_RaySelect obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public OperateRecord_RaySelect __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public PRO.Flat.Vector2? StartPos { get { int o = __p.__offset(4); return o != 0 ? (PRO.Flat.Vector2?)(new PRO.Flat.Vector2()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public PRO.Flat.Vector2? EndPos { get { int o = __p.__offset(6); return o != 0 ? (PRO.Flat.Vector2?)(new PRO.Flat.Vector2()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public string ByRoleGuid { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetByRoleGuidBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetByRoleGuidBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetByRoleGuidArray() { return __p.__vector_as_array<byte>(8); }

  public static void StartOperateRecord_RaySelect(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddStartPos(FlatBufferBuilder builder, Offset<PRO.Flat.Vector2> startPosOffset) { builder.AddStruct(0, startPosOffset.Value, 0); }
  public static void AddEndPos(FlatBufferBuilder builder, Offset<PRO.Flat.Vector2> endPosOffset) { builder.AddStruct(1, endPosOffset.Value, 0); }
  public static void AddByRoleGuid(FlatBufferBuilder builder, StringOffset byRoleGuidOffset) { builder.AddOffset(2, byRoleGuidOffset.Value, 0); }
  public static Offset<PRO.Skill.Flat.OperateRecord_RaySelect> EndOperateRecord_RaySelect(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<PRO.Skill.Flat.OperateRecord_RaySelect>(o);
  }
}


static public class OperateRecord_RaySelectVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*StartPos*/, 8 /*PRO.Flat.Vector2*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*EndPos*/, 8 /*PRO.Flat.Vector2*/, 4, false)
      && verifier.VerifyString(tablePos, 8 /*ByRoleGuid*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
