//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{


    public class PixelColorInfo
    {

        private UnityEngine.Vector4 _color;

        private float _transmittance;

        private float _shininess;

        // 颜色
        public UnityEngine.Vector4 color
        {
            get
            {
                return this._color;
            }
            set
            {
                this._color = value;
            }
        }

        // 透光度
        public float transmittance
        {
            get
            {
                return this._transmittance;
            }
            set
            {
                this._transmittance = value;
            }
        }

        // 反光度
        public float shininess
        {
            get
            {
                return this._shininess;
            }
            set
            {
                this._shininess = value;
            }
        }
    }
}
