// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace PRO.Flat
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct RoleInfoData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static RoleInfoData GetRootAsRoleInfoData(ByteBuffer _bb) { return GetRootAsRoleInfoData(_bb, new RoleInfoData()); }
  public static RoleInfoData GetRootAsRoleInfoData(ByteBuffer _bb, RoleInfoData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public RoleInfoData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Value1 { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Value2 { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Value3 { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Value4(int j) { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int Value4Length { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<int> GetValue4Bytes() { return __p.__vector_as_span<int>(10, 4); }
#else
  public ArraySegment<byte>? GetValue4Bytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public int[] GetValue4Array() { return __p.__vector_as_array<int>(10); }
  public float Value5 { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float Value6 { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float Value7 { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float Value8 { get { int o = __p.__offset(18); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public int Value9 { get { int o = __p.__offset(20); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Value10 { get { int o = __p.__offset(22); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Value11 { get { int o = __p.__offset(24); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Value12 { get { int o = __p.__offset(26); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<PRO.Flat.RoleInfoData> CreateRoleInfoData(FlatBufferBuilder builder,
      int value1 = 0,
      int value2 = 0,
      int value3 = 0,
      VectorOffset value4Offset = default(VectorOffset),
      float value5 = 0.0f,
      float value6 = 0.0f,
      float value7 = 0.0f,
      float value8 = 0.0f,
      int value9 = 0,
      int value10 = 0,
      int value11 = 0,
      int value12 = 0) {
    builder.StartTable(12);
    RoleInfoData.AddValue12(builder, value12);
    RoleInfoData.AddValue11(builder, value11);
    RoleInfoData.AddValue10(builder, value10);
    RoleInfoData.AddValue9(builder, value9);
    RoleInfoData.AddValue8(builder, value8);
    RoleInfoData.AddValue7(builder, value7);
    RoleInfoData.AddValue6(builder, value6);
    RoleInfoData.AddValue5(builder, value5);
    RoleInfoData.AddValue4(builder, value4Offset);
    RoleInfoData.AddValue3(builder, value3);
    RoleInfoData.AddValue2(builder, value2);
    RoleInfoData.AddValue1(builder, value1);
    return RoleInfoData.EndRoleInfoData(builder);
  }

  public static void StartRoleInfoData(FlatBufferBuilder builder) { builder.StartTable(12); }
  public static void AddValue1(FlatBufferBuilder builder, int value1) { builder.AddInt(0, value1, 0); }
  public static void AddValue2(FlatBufferBuilder builder, int value2) { builder.AddInt(1, value2, 0); }
  public static void AddValue3(FlatBufferBuilder builder, int value3) { builder.AddInt(2, value3, 0); }
  public static void AddValue4(FlatBufferBuilder builder, VectorOffset value4Offset) { builder.AddOffset(3, value4Offset.Value, 0); }
  public static VectorOffset CreateValue4Vector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateValue4VectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateValue4VectorBlock(FlatBufferBuilder builder, ArraySegment<int> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateValue4VectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<int>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartValue4Vector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddValue5(FlatBufferBuilder builder, float value5) { builder.AddFloat(4, value5, 0.0f); }
  public static void AddValue6(FlatBufferBuilder builder, float value6) { builder.AddFloat(5, value6, 0.0f); }
  public static void AddValue7(FlatBufferBuilder builder, float value7) { builder.AddFloat(6, value7, 0.0f); }
  public static void AddValue8(FlatBufferBuilder builder, float value8) { builder.AddFloat(7, value8, 0.0f); }
  public static void AddValue9(FlatBufferBuilder builder, int value9) { builder.AddInt(8, value9, 0); }
  public static void AddValue10(FlatBufferBuilder builder, int value10) { builder.AddInt(9, value10, 0); }
  public static void AddValue11(FlatBufferBuilder builder, int value11) { builder.AddInt(10, value11, 0); }
  public static void AddValue12(FlatBufferBuilder builder, int value12) { builder.AddInt(11, value12, 0); }
  public static Offset<PRO.Flat.RoleInfoData> EndRoleInfoData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<PRO.Flat.RoleInfoData>(o);
  }
}


static public class RoleInfoDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Value1*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*Value2*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*Value3*/, 4 /*int*/, 4, false)
      && verifier.VerifyVectorOfData(tablePos, 10 /*Value4*/, 4 /*int*/, false)
      && verifier.VerifyField(tablePos, 12 /*Value5*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 14 /*Value6*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 16 /*Value7*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 18 /*Value8*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 20 /*Value9*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 22 /*Value10*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 24 /*Value11*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 26 /*Value12*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
