// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace PRO.Flat
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct EventData_Int32Data : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public EventData_Int32Data __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Value0 { get { return __p.bb.GetInt(__p.bb_pos + 0); } }
  public double Value1 { get { return __p.bb.GetDouble(__p.bb_pos + 8); } }
  public int Value2 { get { return __p.bb.GetInt(__p.bb_pos + 16); } }
  public int Value3 { get { return __p.bb.GetInt(__p.bb_pos + 20); } }

  public static Offset<PRO.Flat.EventData_Int32Data> CreateEventData_Int32Data(FlatBufferBuilder builder, int Value0, double Value1, int Value2, int Value3) {
    builder.Prep(8, 24);
    builder.PutInt(Value3);
    builder.PutInt(Value2);
    builder.PutDouble(Value1);
    builder.Pad(4);
    builder.PutInt(Value0);
    return new Offset<PRO.Flat.EventData_Int32Data>(builder.Offset);
  }
}

public struct EventData_DoubleData : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public EventData_DoubleData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public double Value0 { get { return __p.bb.GetDouble(__p.bb_pos + 0); } }
  public double Value1 { get { return __p.bb.GetDouble(__p.bb_pos + 8); } }
  public double Value2 { get { return __p.bb.GetDouble(__p.bb_pos + 16); } }
  public double Value3 { get { return __p.bb.GetDouble(__p.bb_pos + 24); } }

  public static Offset<PRO.Flat.EventData_DoubleData> CreateEventData_DoubleData(FlatBufferBuilder builder, double Value0, double Value1, double Value2, double Value3) {
    builder.Prep(8, 32);
    builder.PutDouble(Value3);
    builder.PutDouble(Value2);
    builder.PutDouble(Value1);
    builder.PutDouble(Value0);
    return new Offset<PRO.Flat.EventData_DoubleData>(builder.Offset);
  }
}

public struct RoleInfoData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static RoleInfoData GetRootAsRoleInfoData(ByteBuffer _bb) { return GetRootAsRoleInfoData(_bb, new RoleInfoData()); }
  public static RoleInfoData GetRootAsRoleInfoData(ByteBuffer _bb, RoleInfoData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public RoleInfoData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public PRO.Flat.EventData_Int32Data? Value1 { get { int o = __p.__offset(4); return o != 0 ? (PRO.Flat.EventData_Int32Data?)(new PRO.Flat.EventData_Int32Data()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public PRO.Flat.EventData_Int32Data? Value2 { get { int o = __p.__offset(6); return o != 0 ? (PRO.Flat.EventData_Int32Data?)(new PRO.Flat.EventData_Int32Data()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public PRO.Flat.EventData_Int32Data? Value3 { get { int o = __p.__offset(8); return o != 0 ? (PRO.Flat.EventData_Int32Data?)(new PRO.Flat.EventData_Int32Data()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public PRO.Flat.EventData_Int32Data? Value4 { get { int o = __p.__offset(10); return o != 0 ? (PRO.Flat.EventData_Int32Data?)(new PRO.Flat.EventData_Int32Data()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public PRO.Flat.EventData_Int32Data? Value5 { get { int o = __p.__offset(12); return o != 0 ? (PRO.Flat.EventData_Int32Data?)(new PRO.Flat.EventData_Int32Data()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public PRO.Flat.EventData_DoubleData? Value6 { get { int o = __p.__offset(14); return o != 0 ? (PRO.Flat.EventData_DoubleData?)(new PRO.Flat.EventData_DoubleData()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public PRO.Flat.EventData_DoubleData? Value7 { get { int o = __p.__offset(16); return o != 0 ? (PRO.Flat.EventData_DoubleData?)(new PRO.Flat.EventData_DoubleData()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public PRO.Flat.EventData_Int32Data? Value8(int j) { int o = __p.__offset(18); return o != 0 ? (PRO.Flat.EventData_Int32Data?)(new PRO.Flat.EventData_Int32Data()).__assign(__p.__vector(o) + j * 24, __p.bb) : null; }
  public int Value8Length { get { int o = __p.__offset(18); return o != 0 ? __p.__vector_len(o) : 0; } }
  public PRO.Flat.EventData_DoubleData? Value9 { get { int o = __p.__offset(20); return o != 0 ? (PRO.Flat.EventData_DoubleData?)(new PRO.Flat.EventData_DoubleData()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public PRO.Flat.EventData_DoubleData? Value10 { get { int o = __p.__offset(22); return o != 0 ? (PRO.Flat.EventData_DoubleData?)(new PRO.Flat.EventData_DoubleData()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public PRO.Flat.EventData_DoubleData? Value11 { get { int o = __p.__offset(24); return o != 0 ? (PRO.Flat.EventData_DoubleData?)(new PRO.Flat.EventData_DoubleData()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public PRO.Flat.EventData_Int32Data? Value12 { get { int o = __p.__offset(26); return o != 0 ? (PRO.Flat.EventData_Int32Data?)(new PRO.Flat.EventData_Int32Data()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public PRO.Flat.Vector2Int? MouldSize { get { int o = __p.__offset(28); return o != 0 ? (PRO.Flat.Vector2Int?)(new PRO.Flat.Vector2Int()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public PRO.Flat.Vector2Int? MouldOffset { get { int o = __p.__offset(30); return o != 0 ? (PRO.Flat.Vector2Int?)(new PRO.Flat.Vector2Int()).__assign(o + __p.bb_pos, __p.bb) : null; } }

  public static void StartRoleInfoData(FlatBufferBuilder builder) { builder.StartTable(14); }
  public static void AddValue1(FlatBufferBuilder builder, Offset<PRO.Flat.EventData_Int32Data> value1Offset) { builder.AddStruct(0, value1Offset.Value, 0); }
  public static void AddValue2(FlatBufferBuilder builder, Offset<PRO.Flat.EventData_Int32Data> value2Offset) { builder.AddStruct(1, value2Offset.Value, 0); }
  public static void AddValue3(FlatBufferBuilder builder, Offset<PRO.Flat.EventData_Int32Data> value3Offset) { builder.AddStruct(2, value3Offset.Value, 0); }
  public static void AddValue4(FlatBufferBuilder builder, Offset<PRO.Flat.EventData_Int32Data> value4Offset) { builder.AddStruct(3, value4Offset.Value, 0); }
  public static void AddValue5(FlatBufferBuilder builder, Offset<PRO.Flat.EventData_Int32Data> value5Offset) { builder.AddStruct(4, value5Offset.Value, 0); }
  public static void AddValue6(FlatBufferBuilder builder, Offset<PRO.Flat.EventData_DoubleData> value6Offset) { builder.AddStruct(5, value6Offset.Value, 0); }
  public static void AddValue7(FlatBufferBuilder builder, Offset<PRO.Flat.EventData_DoubleData> value7Offset) { builder.AddStruct(6, value7Offset.Value, 0); }
  public static void AddValue8(FlatBufferBuilder builder, VectorOffset value8Offset) { builder.AddOffset(7, value8Offset.Value, 0); }
  public static void StartValue8Vector(FlatBufferBuilder builder, int numElems) { builder.StartVector(24, numElems, 8); }
  public static void AddValue9(FlatBufferBuilder builder, Offset<PRO.Flat.EventData_DoubleData> value9Offset) { builder.AddStruct(8, value9Offset.Value, 0); }
  public static void AddValue10(FlatBufferBuilder builder, Offset<PRO.Flat.EventData_DoubleData> value10Offset) { builder.AddStruct(9, value10Offset.Value, 0); }
  public static void AddValue11(FlatBufferBuilder builder, Offset<PRO.Flat.EventData_DoubleData> value11Offset) { builder.AddStruct(10, value11Offset.Value, 0); }
  public static void AddValue12(FlatBufferBuilder builder, Offset<PRO.Flat.EventData_Int32Data> value12Offset) { builder.AddStruct(11, value12Offset.Value, 0); }
  public static void AddMouldSize(FlatBufferBuilder builder, Offset<PRO.Flat.Vector2Int> mouldSizeOffset) { builder.AddStruct(12, mouldSizeOffset.Value, 0); }
  public static void AddMouldOffset(FlatBufferBuilder builder, Offset<PRO.Flat.Vector2Int> mouldOffsetOffset) { builder.AddStruct(13, mouldOffsetOffset.Value, 0); }
  public static Offset<PRO.Flat.RoleInfoData> EndRoleInfoData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<PRO.Flat.RoleInfoData>(o);
  }
}


static public class RoleInfoDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Value1*/, 24 /*PRO.Flat.EventData_Int32Data*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*Value2*/, 24 /*PRO.Flat.EventData_Int32Data*/, 8, false)
      && verifier.VerifyField(tablePos, 8 /*Value3*/, 24 /*PRO.Flat.EventData_Int32Data*/, 8, false)
      && verifier.VerifyField(tablePos, 10 /*Value4*/, 24 /*PRO.Flat.EventData_Int32Data*/, 8, false)
      && verifier.VerifyField(tablePos, 12 /*Value5*/, 24 /*PRO.Flat.EventData_Int32Data*/, 8, false)
      && verifier.VerifyField(tablePos, 14 /*Value6*/, 32 /*PRO.Flat.EventData_DoubleData*/, 8, false)
      && verifier.VerifyField(tablePos, 16 /*Value7*/, 32 /*PRO.Flat.EventData_DoubleData*/, 8, false)
      && verifier.VerifyVectorOfData(tablePos, 18 /*Value8*/, 24 /*PRO.Flat.EventData_Int32Data*/, false)
      && verifier.VerifyField(tablePos, 20 /*Value9*/, 32 /*PRO.Flat.EventData_DoubleData*/, 8, false)
      && verifier.VerifyField(tablePos, 22 /*Value10*/, 32 /*PRO.Flat.EventData_DoubleData*/, 8, false)
      && verifier.VerifyField(tablePos, 24 /*Value11*/, 32 /*PRO.Flat.EventData_DoubleData*/, 8, false)
      && verifier.VerifyField(tablePos, 26 /*Value12*/, 24 /*PRO.Flat.EventData_Int32Data*/, 8, false)
      && verifier.VerifyField(tablePos, 28 /*MouldSize*/, 8 /*PRO.Flat.Vector2Int*/, 4, false)
      && verifier.VerifyField(tablePos, 30 /*MouldOffset*/, 8 /*PRO.Flat.Vector2Int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
